### PR TITLE
Fix advanceIfNeeded into gaps for Roaring64Bitmap

### LINKED ISSUE #488: Roaring64Bitmap advanceIfNeeded into gaps returns the too far into the next range.
If you set two ranges of values `A-C, E-F` and then advance the iterator to `D` I would expect the peekNext/Next to return `E` where I am getting `E+`

Thus the 64 bit Code fails, where the 32 bit code works.

```
	@Test
	public void testRoaring64BitsetAdvance() {
		Roaring64Bitmap bitset = new Roaring64Bitmap();

		bitset.add(2000000000L, 2200000000L);
		bitset.add(4000000000L, 4300000000L);

		var bitIt = bitset.getLongIterator();

		// first value is first 2000000000L
		assertEquals(2000000000L, bitIt.peekNext());
		assertEquals(2000000000L, bitIt.next());

		// second value is next 2100000000L
		assertTrue(bitset.contains(2100000000L));
		bitIt.advanceIfNeeded(2100000000L);
		assertEquals(2100000000L, bitIt.peekNext());
		assertEquals(2100000000L, bitIt.next());

		// advancing to a value not in ether range 2300000000L should go to the first value of second range (aka the third value)
		assertFalse(bitset.contains(2300000000L));
		bitIt.advanceIfNeeded( 2300000000L);

		// this steps to 4000000000L  so the next fails. and returns something like: 4299962112
		assertEquals(4000000000L, bitIt.peekNext());

		// third value 4000000000L
		assertTrue(bitset.contains( 4000000000L));
		bitIt.advanceIfNeeded( 4000000000L);
		assertEquals(4000000000L, bitIt.peekNext());
		assertEquals(4000000000L, bitIt.next());

	}

	@Test
	public void testRoaringBitsetAdvance() {
		RoaringBitmap bitset = new RoaringBitmap();

		bitset.add(2000000, 2200000);
		bitset.add(4000000, 4300000);

		var bitIt = bitset.getIntIterator();

		// first value is first 2000000000L
		assertEquals(2000000, bitIt.peekNext());
		assertEquals(2000000, bitIt.next());

		// second value is next 2100000000L
		assertTrue(bitset.contains(2100000));
		bitIt.advanceIfNeeded(2100000);
		assertEquals(2100000, bitIt.peekNext());
		assertEquals(2100000, bitIt.next());

		// advancing to a value not in ether range 2300000 should go to the first value of second range (aka the third value)
		assertFalse(bitset.contains(2300000));
		bitIt.advanceIfNeeded( 2300000);

		// this steps to 4000000  works
		assertEquals(4000000, bitIt.peekNext());

		// third value 4000000
		assertTrue(bitset.contains( 4000000));
		bitIt.advanceIfNeeded( 4000000);
		assertEquals(4000000, bitIt.peekNext());
		assertEquals(4000000, bitIt.next());
	}
```

**RoaringBitmap version:**
0.9.10

**Java version:**
  zsrc11.48.21-jdk11.0.11 aaa599031ee78a8b4006c475659621d448509b33
  OpenJSSE 1.1.6 b1b08ea9c6becef6fa5642e85857acef2135e7d2

### PR DESCRIPTION
**Pull request by larsk-db**
Fixes #488 .

@simeonpilgrim I hope you don't mind me verbatim copying your test cases here?

### CODE REVIEW

**Comment by simeonpilgrim** [comment]
@larsk-db super happy. I posted the issue think I might "solve it" but first thought I would open an issue, and then a few hours later was lost in the guts of the ART ponder what any of it did. So if the test case helped you solve it I am beyond pleased.

If I could be so bold to ask if there could be a release made in the near future, that would be magic.

**Comment by larsk-db** [comment]
I found another issue when the gap has another container before it. Let me fix that, too.

**Comment by larsk-db** [comment]
Alright, I fixed everything i found.

This is ready for review now.

**Comment by lemire** [comment]
@simeonpilgrim  Would you review this PR in its final form?

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java [hunk 1]
```diff
@@ -863,10 +864,12 @@ public void advanceIfNeeded(long minval) {
         }
       }
 
-      // advance inner
-      char low = LongUtils.lowPart(minval);
-      charIterator.advanceIfNeeded(low);
-      hasNextCalled = false;
+      if (Arrays.equals(this.high, minHigh)) {
```
Comment (weijietong) [inline RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:867]: seems no need to add this additional conditional judgement

Comment (simeonpilgrim) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:867]: I agree that commenting out the IF check, the tests still pass. And ponder if the check was to be left, if the `Arrays.equals` should be replace with the `compareHigh` to be consistent.

File: RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java [hunk 2]
```diff
@@ -1739,6 +1739,201 @@ public void testEmptySkipsReverse() {
...
+    // should go to the first value of third range
+    assertFalse(bitset.contains(pgapNextContainer));
+    bitIt.advanceIfNeeded(pgapNextContainer);
+
+    assertEquals(b1e - 1L, bitIt.peekNext());
+
+    bitIt.advanceIfNeeded(b1e);
+    assertEquals(b1e - 1L, bitIt.peekNext());
+    assertEquals(b1e - 1L, bitIt.next());
+  }
```
Comment (simeonpilgrim) [inline RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java:1936]: at this point in the test I wondered "what happens if I advance past the last value" so insert some more code
```
    System.out.println(bitIt.peekNext());
    System.out.println(b3e);
    bitIt.advanceIfNeeded(b3e);
    assertFalse(bitset.contains(b3e));
    System.out.println(bitIt.peekNext());
    assertFalse(bitIt.hasNext());
```

surprising to me the assert fails. with the sout's I show these values:
```
2000018498
6000018500
2000018498
```

which makes sense from the perspective of there is "no such value, thus no where to advance to" but the example in the abstract class is a merge join, and that would break if the bitmap iterator fails to advance to the end, and thus would spin forever. I didn't test this with the 32bit code, nor on the original code, to see if it is a side effect of the change.

**Review by simeonpilgrim — CHANGES_REQUESTED** [review]
with the advance passed end not working, the rest of my test suite does run, as we rely on that functionality.

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java (hunk 1 above)
Comment (simeonpilgrim) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:867]: scratch my high comment here, I just observed that the compareHigh are doing >= or <= in the forward/reverse iterators, where this was just looking for equality.

Comment (simeonpilgrim) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:867]: also as I rewrite the code to understand what it's doing, the `IF` here (line 867) is needed as the compareHigh on line 842 will branch into this line when we step over the block we are looking for at which point we want the first value, not to step forward for the lower parts on the wrong upper block.

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java [hunk 3]
```diff
@@ -863,10 +864,12 @@ public void advanceIfNeeded(long minval) {
         }
       }
```
Comment (simeonpilgrim) [inline RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:865]: the only thing I honestly think I notice / question is on line 861 ( which I am not able to select ) the 
```
            } else {         
     return;      
      }
```
this is the else to the keyIte.hasNext() being false, I question if the "high level interator" after the seek has no next, is `charIterator` is not set null.

thus a call to hasNext(), which will check the old stale `charIterator` might say yes.

unless

**Comment by simeonpilgrim** [comment]
Ok, so I pulled this code into our tool, which is failing, and I copied the values I am getting from my merge join into this new test:

```
  @Test
  public void testSimeonTake2() {
    Roaring64Bitmap bitset = new Roaring64Bitmap();
    bitset.add(2104959186L, 2147483614L);
    bitset.add(4273492378L, 4294967214L);

    PeekableLongIterator bitIt = bitset.getLongIterator();

    //bitId: 2104959186 dimId: 21262214
    bitIt.peekNext();
    //dimIt.advanceIfNeeded(bitId) 2104959186
    //bitId: 2104959186 dimId: 2104959186
    bitIt.peekNext();
    bitIt.next();

    //bitId: 2104959187 dimId: 2126221400
    bitIt.peekNext();
    //bitIt.advanceIfNeeded(dimId) 2126221400
    bitIt.advanceIfNeeded(2126221400L);

    //bitId: 2126221400 dimId: 2126221400
    bitIt.peekNext();
    bitIt.next();

    //bitId: 2126221401 dimId: 2168958450
    bitIt.peekNext();

    //bitIt.advanceIfNeeded(dimId) 2168958450
    assertTrue(bitIt.hasNext());
    long v1 = bitIt.peekNext();
    assertTrue(v1 < 2168958450L );
    bitIt.advanceIfNeeded(2168958450L);

    assertTrue(bitIt.hasNext());
    long v2 = bitIt.peekNext();

    assertNotEquals(v1,v2);

    //assertFalse(2168958450L > v2);
    //bitId: 2105016320 dimId: 2168958450
    assertNotEquals(2168958450L, bitIt.peekNext());

    bitIt.advanceIfNeeded(2168958450L);

    assertTrue(bitIt.hasNext());
    long v3 = bitIt.peekNext();

    System.out.println(String.format("v1 %d v2 %d v3 %d", v1, v2, v3));

    assertNotEquals(v2,v3); // equaling 2105016320

    //bitIt.advanceIfNeeded(dimId) 2168958450
  }
```
the commented out code is my my merge test that looks like:

```
		var bitIt = bitset.getLongIterator();
		var dimIt = dimension.getIdIterator();

		long lastbit = -2;
		long lastdim = -2;
		while (bitIt.hasNext() && dimIt.hasNext()) {
			long bitId = bitIt.peekNext();
			long dimId = dimIt.peekNext();
			assertNotEquals(lastbit, bitId);
			assertNotEquals(lastdim, dimId);

			System.out.println(String.format("  bitId: %d dimId: %d", bitId, dimId));
			if (bitId == dimId){
				// because we were peeking before now consume those values
				bitIt.next();
				dimIt.next();

				// and now "do the merge join action"
				words.add(dimension.getValueFromId(bitId));
			} else if (bitId > dimId) {
				System.out.println(String.format("    dimIt.advanceIfNeeded(bitId) %d", bitId));
				lastdim = dimId;
				// bit id is beyond dim id, so step dim forward
				dimIt.advanceIfNeeded(bitId);
			} else {
				System.out.println(String.format("    bitIt.advanceIfNeeded(dimId) %d", dimId));
				lastbit = bitId;
				// dim id is beyond bit id, so step bit forward
				bitIt.advanceIfNeeded(dimId);
			}
		}

```

the out had the values going backwards which is blowing my mind...
`v1 2126221401 v2 2105016320 v3 2105016320` and then the value `2105016320` repeats indefinitly.

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java (hunk 1 above)
Comment (larsk-db) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:867]: Yes, we definitely need this. This is what caused the first bug @simeonpilgrim originally reported.

File: RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java (hunk 2 above)
Comment (larsk-db) [reply RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java:1936]: Is there some action item here, or I can I mark this as resolved?

Comment (simeonpilgrim) [reply RoaringBitmap/src/test/java/org/roaringbitmap/longlong/TestRoaring64Bitmap.java:1936]: resolved.

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java (hunk 3 above)
Comment (larsk-db) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:865]: I agree. I'm setting `charIterator = null;` there, so that `hasNext()` will fail there. I'm also thinking we actually gotta set `hasNextCalled = false` there, to avoid a potential `NullPointerException` in `next()` and `peekNext()` afterwards.

Comment (simeonpilgrim) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:865]: when I rewrote it today, I stripped all the `hasNextCalled` variables, and always just called `hasNext()` at the correct time to avoid stale variables. To which end I am not sure if `hasNextCalled` is there as a "performance improvement" but it doesn't seem like it makes the code stable verse the "cost" of calling `charIterator != null && charIterator.hasNext()`.

Which speaking of if hasNext is reordered to have the return true path first, then the other to larger iterate across the outer iterators can be just one while block, as they are the same body.

Comment (larsk-db) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:865]: You are right. Reordering and dropping `hasNextCalled` makes the code a lot simpler at the cost of a few extra comparisons. I feel this is worth it, considering how complicated the rest is already. What do you think @weijietong ?

**Comment by larsk-db** [comment]
> the out had the values going backwards which is blowing my mind...
> `v1 2126221401 v2 2105016320 v3 2105016320` and then the value `2105016320` repeats indefinitly.

Ok, I finally figured out what's going wrong here. It's still the same issue I noted last week, I just didn't understand the extent of the problem. I'm going to have to change the way I select children during traversal when no child actually matches the key. This is going to take me a wee bit (gotta do some other work, too :D).

I'll ping you again, when I got it working @simeonpilgrim.

**Comment by larsk-db** [comment]
@simeonpilgrim This is ready for review.

I changed the `runLength` in the tests I introduce before to cover the situation that occurred in your last test scenario above.

File: RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java [hunk 4]
```diff
@@ -79,6 +79,11 @@ public int getChildPos(byte k) {
     throw new UnsupportedOperationException();
   }
 
+  @Override
+  public SearchResult getNearestChildPos(byte key) {
```
Comment (simeonpilgrim) [inline RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java:83]: I really like this, I had gone down the path of looping while not "direction greater".

Over all I really like this work, I had some extra tests I had added to  ArtTest.java which all pass with this change, and all my external project tests pass, so thank you so much for that fixes.

my one question is should the getNearestChildPos functions (for each node type) have some tests explicitly written from them. The code looked a little hairy, (aka I've not read each of the node types implementation code). I am happy to write those tests to understand them, and post them on another PR, unless the code is "simple once understood".

Anyways here are the tests I had for testing the seek of the LeafNodeIterator, if you want to include them (or not, or would just like them as another PR).

```

  @Test
  public void testNodeSeek() {
    byte[] key0 = new byte[]{1, 2, 3, 4, 5, 0};
    byte[] key1 = new byte[]{1, 2, 3, 4, 5, 1};
    byte[] key2 = new byte[]{1, 2, 3, 4, 5, 2};
    Art art = new Art();
    insert5PrefixCommonBytesIntoArt(art, 3);
    LeafNodeIterator lnIt = art.leafNodeIterator(false, null);
    boolean hasNext = lnIt.hasNext();

    // brand new iterator is pointing at first key "0"
    Assertions.assertTrue(hasNext);
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the current spot is fine
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the next spot "1" is fine
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    // seeking to the next spot "2" is fine
    lnIt.seek(LongUtils.toLong(key2, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));
    Assertions.assertTrue(BytesUtil.same(lnIt.next().getKeyBytes(), key2));
    Assertions.assertFalse(lnIt.hasNext());

    // seeking to the prior "1" takes you there.. so this needs to be guarded against, in higher levels
    // (as it is)
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));
  }

  @Test
  public void testNodeSeekReverse() {
    byte[] key0 = new byte[]{1, 2, 3, 4, 5, 0};
    byte[] key1 = new byte[]{1, 2, 3, 4, 5, 1};
    byte[] key2 = new byte[]{1, 2, 3, 4, 5, 2};
    Art art = new Art();
    insert5PrefixCommonBytesIntoArt(art, 3);
    LeafNodeIterator lnIt = art.leafNodeIterator(true, null);
    boolean hasNext = lnIt.hasNext();

    // brand new iterator is pointing at first key "2"
    Assertions.assertTrue(hasNext);
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));

    // seeking to the current spot is fine
    lnIt.seek(LongUtils.toLong(key2, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));

    // seeking to the next spot "1" is fine
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    // seeking to the next spot "0" is fine
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
    Assertions.assertTrue(BytesUtil.same(lnIt.next().getKeyBytes(), key0));
    Assertions.assertFalse(lnIt.hasNext());

    // seeking to the prior "1" takes you there.. so this needs to be guarded against, in higher levels
    // (as it is)
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));
  }

  @Test
  public void testNodeSeekOverGaps() {
    byte[] start0 = new byte[]{0, 2, 3, 4, 5, 0};
    byte[] key0 = new byte[]{1, 2, 3, 4, 5, 0};
    byte[] gap1 = new byte[]{1, 2, 3, 4, 5, 1};
    byte[] key1 = new byte[]{1, 2, 3, 4, 5, 2};
    byte[] gap2 = new byte[]{1, 2, 3, 4, 5, 3};
    byte[] key2 = new byte[]{1, 2, 3, 4, 5, 4};
    byte[] end1 = new byte[]{2, 2, 3, 4, 5, 4};

    Art art = new Art();
    insert5PrefixCommonWithGapBytesIntoArt(art, 3);
    LeafNodeIterator lnIt = art.leafNodeIterator(false, null);
    boolean hasNext = lnIt.hasNext();

    // brand new iterator is pointing at first key "0"
    Assertions.assertTrue(hasNext);
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the current spot is fine
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the next spot "1" is fine
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    // seeking to the next spot "2" is fine
    lnIt.seek(LongUtils.toLong(key2, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));
    Assertions.assertTrue(BytesUtil.same(lnIt.next().getKeyBytes(), key2));
    Assertions.assertFalse(lnIt.hasNext());

    // seeking to the prior "1" takes you there.. so this needs to be guarded against, in higher levels
    // (as it is)
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // NOW TO ENTER THE GAP ZONE... we should get "1" as it's after gap "1"
    lnIt.seek(LongUtils.toLong(gap1, (char) 0));

    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    lnIt.seek(LongUtils.toLong(gap2, (char) 0));

    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));

    // going to past the last value should "work", there just should be nothing to get next...
    lnIt.seek(LongUtils.toLong(end1, (char) 0));
    Assertions.assertFalse(lnIt.hasNext());

    // going the before the first should "return" the first
    lnIt.seek(LongUtils.toLong(start0, (char)0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

  }

  @Test
  public void testNodeSeekOverGapsReverse() {
    byte[] start0 = new byte[]{2, 2, 3, 4, 5, 0};
    byte[] key0 = new byte[]{1, 2, 3, 4, 5, 4};
    byte[] gap1 = new byte[]{1, 2, 3, 4, 5, 3};
    byte[] key1 = new byte[]{1, 2, 3, 4, 5, 2};
    byte[] gap2 = new byte[]{1, 2, 3, 4, 5, 1};
    byte[] key2 = new byte[]{1, 2, 3, 4, 5, 0};
    byte[] end1 = new byte[]{0, 2, 3, 4, 5, 0};

    Art art = new Art();
    insert5PrefixCommonWithGapBytesIntoArt(art, 3);
    LeafNodeIterator lnIt = art.leafNodeIterator(true, null);
    boolean hasNext = lnIt.hasNext();

    // brand new iterator is pointing at first key "0"
    Assertions.assertTrue(hasNext);
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the current spot is fine
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // seeking to the next spot "1" is fine
    lnIt.seek(LongUtils.toLong(key1, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    // seeking to the next spot "2" is fine
    lnIt.seek(LongUtils.toLong(key2, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));
    Assertions.assertTrue(BytesUtil.same(lnIt.next().getKeyBytes(), key2));
    Assertions.assertFalse(lnIt.hasNext());

    // seeking to the prior "1" takes you there.. so this needs to be guarded against, in higher levels
    // (as it is)
    lnIt.seek(LongUtils.toLong(key0, (char) 0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));

    // NOW TO ENTER THE GAP ZONE... we should get "1" as it's after gap "1"
    lnIt.seek(LongUtils.toLong(gap1, (char) 0));

    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));

    lnIt.seek(LongUtils.toLong(gap2, (char) 0));

    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
    Assertions.assertFalse(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key1));
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key2));

    // going to past the last value should "work", there just should be nothing to get next...
    lnIt.seek(LongUtils.toLong(end1, (char) 0));
    Assertions.assertFalse(lnIt.hasNext());

    // going the before the first should "return" the first
    lnIt.seek(LongUtils.toLong(start0, (char)0));
    Assertions.assertTrue(lnIt.hasNext());
    Assertions.assertTrue(BytesUtil.same(lnIt.peekNext().getKeyBytes(), key0));
  }
```

**Review by simeonpilgrim — APPROVED** [review]
In the end you used a larger scalpel than I was weaving though the code, but at the same time, your solution solved my edge cases. Thank you.

**Comment by larsk-db** [comment]
> In the end you used a larger scalpel than I was weaving though the code, but at the same time, your solution solved my edge cases. Thank you.

Yeah, it's my bad for implementing this wrong in the first place. I was trying to reuse as much code from `contains` as possible, but there are just many more cases we need to care about for the iterator than `contains` does. So thank *you* for finding all these issues and providing test cases!

File: RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java [hunk 5]
```diff
@@ -905,6 +908,11 @@ PeekableCharIterator getIterator(Container container) {
     boolean compare(long next, long val) {
```
[the remark this answers is not in the document]
Comment (larsk-db) [reply RoaringBitmap/src/main/java/org/roaringbitmap/longlong/Roaring64Bitmap.java:879]: Yeah, it makes sense for this to be a separate issue.

File: RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java (hunk 4 above)
Comment (larsk-db) [reply RoaringBitmap/src/main/java/org/roaringbitmap/art/LeafNode.java:83]: I think all those extra tests are a great idea. This code is so involved I don't think it can possibly be tested enough.

Would you mind adding anything you can think of (the ones you posted and the per node tests you suggested) in a separate PR? I think it makes more sense for them to come from you instead of me continuing to copy&paste your work into my commits :D Also maybe this PR is monstrous enough as is^^

File: RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java [hunk 6]
```diff
@@ -207,4 +208,85 @@ public void testEmptySkips() {
     PeekableIntIterator it = bitmap.getIntIterator();
     it.advanceIfNeeded(0);
   }
+
+  @Test
+  public void testSkipIntoGaps() {
+    RoaringBitmap bitset = new RoaringBitmap();
```
Comment (richardstartin) [inline RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java:214]: More tests are always welcome, of course, but is this just a sanity check to verify the same bug wasn't also in the 32 bit implementation?

Comment (larsk-db) [reply RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java:214]: Yes, I wanted to make sure it's not a problem with the containers, but with the ART.

Comment (lemire) [reply RoaringBitmap/src/test/java/org/roaringbitmap/TestIterators.java:214]: This sounds like a good idea.

**Comment by lemire** [comment]
Is the consensus that we should merge this now?

**Comment by weijietong** [comment]
I agree with @simeonpilgrim to add more tests to cover different node types to `getNearestChildPos` method. As @simeonpilgrim is giving more tests to continue this PR. I give +1 to this PR to let the work to continue.
