### PR TITLE
Ornot #376

### LINKED ISSUE #376: Corner cases in orNot
Found a quite straightforward bug:

```java
long len = 3L;
long orLen = 3L;

RoaringBitmap one = new RoaringBitmap();
RoaringBitmap other = new RoaringBitmap();
other.add(0L, len);

one.orNot(other, orLen);
```

This throws an `ArrayIndexOutOfBoundsException` for all `len >= 3` and `orLen == len` (funnily enough, the error does not occur if `orLen != len`).

Trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.roaringbitmap.RunContainer.getValue(RunContainer.java:1066)
	at org.roaringbitmap.RunContainer.and(RunContainer.java:387)
	at org.roaringbitmap.Container.and(Container.java:87)
	at org.roaringbitmap.Container.iorNot(Container.java:542)
	at org.roaringbitmap.Container.iorNot(Container.java:560)
	at org.roaringbitmap.RoaringBitmap.orNotHandleRemainingOtherContainers(RoaringBitmap.java:1373)
	at org.roaringbitmap.RoaringBitmap.orNot(RoaringBitmap.java:1468)
```
Tested with 0.8.14

### PR DESCRIPTION
**Pull request by richardstartin**
Fix #376

1. add an emptiness test to RunContainer.and(RunContainer)
2. Special case check when `rangeEnd` is zero
3. stop empty containers from getting into the bitmap during orNot, resulting in whatever happens to be in an empty container being considered.
4. Add a comment to clarify the behaviour that the bitmap is truncated at `rangeEnd` (rightly or wrongly).

Does not change semantics

### CODE REVIEW

**Comment by lemire** [comment]
I think that the decision taken in https://github.com/RoaringBitmap/RoaringBitmap/issues/376 was not change the semantics. So this PR is presumably waiting to be updated.

**Comment by richardstartin** [comment]
I thought we would change the semantics, but I haven’t done it yet.

**Comment by lemire** [comment]
@richardstartin Thank you. I just wanted to leave a trace so that we know where we are at.

**Comment by richardstartin** [comment]
@lemire 

I have rewritten the method to observe the new semantics. The method adopts a heuristic that the array is almost guaranteed to grow, except in some degenerate cases, so always allocates a new array.

File: RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java [hunk 1]
```diff
@@ -1338,248 +1338,78 @@ public static RoaringBitmap andNot(final RoaringBitmap x1, final RoaringBitmap x
...
-      dest.highLowContainer.append(s2, Container.rangeOfOnes(0, lastSize + 1));
-    }
-  }
-
   /**
    * In-place bitwise ORNOT operation. The current bitmap is modified.
    *
    * @param other the other bitmap
-   * @param rangeEnd end point of the range (exclusive)
+   * @param rangeEnd end point of the range (exclusive); values beyond this range in
```
Comment (lemire) [inline RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java:1345]: There may be be an extra "in" in this sentence.

Comment (richardstartin) [reply RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java]: yes, removed this now (semantics changed)

**Comment by lemire** [comment]
+1

You can merge this as far as I am concerned.

**Comment by richardstartin** [comment]
I'm putting something in to guard against `orNot` with full bitmaps blowing up, and will run some benchmarks to check it is better or any regression is < 10% on the status quo.

File: RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java [hunk 2]
```diff
@@ -1338,248 +1338,86 @@ public static RoaringBitmap andNot(final RoaringBitmap x1, final RoaringBitmap x
...
-          answer.highLowContainer.append(s2,
-                  Container.rangeOfOnes(0, containerLast + 1));
-        }
-        s2++;
-      } else { 
-        throw new IllegalStateException("This is a bug. Please report to github");
-      }
+    // it's almost certain that the bitmap will grow, so make a conservative overestimate,
+    // this avoids temporary allocation, and can trim afterwards
+    int maxSize = Math.min(maxKey + 1 + remainder - correction + highLowContainer.size, 0x10000);
```
Comment (richardstartin) [inline RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java:1371]: @lemire I think this estimate is guaranteed to provide a large enough array. Can you convince me otherwise?

Comment (richardstartin) [reply RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java:1371]: It's hard to read in the diff, `correction` is the number of containers on the RHS which are full. `remainder` is the number of containers on the LHS beyond the range end.

**Comment by richardstartin** [comment]
This is faster (Ubuntu 18, JDK11, microbenchmarks may not be representative of actual performance).

Before (3 data sets causes AIOOBE :-1: ):
```
Benchmark                                          (dataset)  Mode  Cnt       Score       Error  Units
RealDataBenchmarkOrNot.pairwiseOrNot           census-income  avgt    5   14287.869 ±   572.691  us/op
RealDataBenchmarkOrNot.pairwiseOrNot              census1881  avgt    5   11257.485 ±   511.279  us/op
RealDataBenchmarkOrNot.pairwiseOrNot           dimension_003  avgt    5  108631.069 ±  8026.821  us/op
RealDataBenchmarkOrNot.pairwiseOrNot           dimension_033  avgt    5   16226.913 ±   753.823  us/op
RealDataBenchmarkOrNot.pairwiseOrNot            uscensus2000  avgt    5   23824.822 ± 35955.458  us/op
RealDataBenchmarkOrNot.pairwiseOrNot         weather_sept_85  avgt    5   36488.019 ±  4292.528  us/op
RealDataBenchmarkOrNot.pairwiseOrNot      wikileaks-noquotes  avgt    5   14058.672 ±  1940.563  us/op
RealDataBenchmarkOrNot.pairwiseOrNot       census-income_srt  avgt    5   10181.575 ±   517.144  us/op
RealDataBenchmarkOrNot.pairwiseOrNot  wikileaks-noquotes_srt  avgt    5   10361.382 ±   548.670  us/op
```

After:

```
Benchmark                                          (dataset)  Mode  Cnt      Score      Error  Units
RealDataBenchmarkOrNot.pairwiseOrNot           census-income  avgt    5  15262.530 ± 2595.704  us/op
RealDataBenchmarkOrNot.pairwiseOrNot              census1881  avgt    5   6800.306 ±  323.475  us/op
RealDataBenchmarkOrNot.pairwiseOrNot           dimension_008  avgt    5  49573.086 ± 2517.147  us/op
RealDataBenchmarkOrNot.pairwiseOrNot           dimension_003  avgt    5  58861.510 ± 1395.904  us/op
RealDataBenchmarkOrNot.pairwiseOrNot           dimension_033  avgt    5  13281.648 ±  380.843  us/op
RealDataBenchmarkOrNot.pairwiseOrNot            uscensus2000  avgt    5   7706.333 ±   92.568  us/op
RealDataBenchmarkOrNot.pairwiseOrNot         weather_sept_85  avgt    5  37008.787 ± 7962.414  us/op
RealDataBenchmarkOrNot.pairwiseOrNot      wikileaks-noquotes  avgt    5  10999.235 ±  931.082  us/op
RealDataBenchmarkOrNot.pairwiseOrNot       census-income_srt  avgt    5   9431.580 ±  362.692  us/op
RealDataBenchmarkOrNot.pairwiseOrNot          census1881_srt  avgt    5   8562.199 ±  107.020  us/op
RealDataBenchmarkOrNot.pairwiseOrNot     weather_sept_85_srt  avgt    5  20442.076 ±  623.475  us/op
RealDataBenchmarkOrNot.pairwiseOrNot  wikileaks-noquotes_srt  avgt    5   7694.901 ±  627.728  us/op


```

File: RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java (hunk 2 above)
Comment (richardstartin) [reply RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java:1371]: @lemire if you can convince yourself this is correct - I believe it is - please merge.

Comment (lemire) [reply RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java:1371]: Yep.

**Comment by lemire** [comment]
Merging. I will issue a release as well.
